<?php
/**
 *  Copyright © iMi digital GmbH, based on work by MageSpecialist
 *  See LICENSE for license details.
 */
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var $block IMI\FriendlyCaptcha\Block\Frontend\FriendlyCaptcha */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $secureRenderer SecureHtmlRenderer */

$endpoint = $block->getPuzzleEndpoint();
$widgetId = $block->getWidgetId();
?>
<div id="<?= $escaper->escapeHtmlAttr($widgetId) ?>"
     class="frc-captcha"
     data-sitekey="<?= $escaper->escapeHtmlAttr($block->getSiteKey()) ?>"
     <?php if ($endpoint !== ''): ?>
         data-puzzle-endpoint="<?= $escaper->escapeUrl($endpoint) ?>"
     <?php endif; ?>
     data-lang="<?= $escaper->escapeHtmlAttr($block->getLang()) ?>"
     data-callback="captchaSolved_<?= $escaper->escapeHtmlAttr($widgetId) ?>"
></div>
<?php
$scriptString = <<<SCRIPT
    'use strict';

    document.addEventListener('DOMContentLoaded', function () {
        function setButtonDisabled(disabled) {
            const button = Array
                .from(document.getElementById('{$widgetId}').closest('form').elements)
                .find(el => el.type === 'submit');
            if (!button) {
                return;
            }
            button.disabled = disabled;
        }

        setButtonDisabled(true);

        window.captchaSolved_{$widgetId} = function () {
            setButtonDisabled(false);
        }
    });
    SCRIPT;
?>
<?= /** noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>
