<?php
/**
 *  Copyright © iMi digital GmbH, based on work by MageSpecialist
 *  See LICENSE for license details.
 */
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var $block IMI\FriendlyCaptcha\Block\Frontend\FriendlyCaptcha */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $secureRenderer SecureHtmlRenderer */

$endpoint = $block->getPuzzleEndpoint();
$widgetId = $block->getWidgetId();
?>
<div id="<?= $escaper->escapeHtmlAttr($widgetId) ?>"
     class="frc-captcha"
     data-sitekey="<?= $escaper->escapeHtmlAttr($block->getSiteKey()) ?>"
     <?php if ($endpoint !== ''): ?>
         data-api-endpoint="<?= $escaper->escapeUrl($endpoint) ?>"
     <?php endif; ?>
></div>
<?php
$scriptString = <<<JS
    'use strict';

    document.addEventListener('DOMContentLoaded', function () {
        function setButtonDisabled(disabled) {
            const button = Array
                .from(document.getElementById('{$widgetId}').closest('form').elements)
                .find(el => el.type === 'submit');
            if (!button) {
                return;
            }
            button.disabled = disabled;
        }

        setButtonDisabled(true);

        document.getElementById('{$widgetId}').addEventListener('frc:widget.statechange', function (event) {
            const detail = event.detail;
            if (detail.state === 'completed') { 
                setButtonDisabled(false);
            } else if (detail.state === 'error') {
                console.error(detail.error);
                // It is best practice to enable your submit button when an error occurs.
                setButtonDisabled(false);
            } else {
              setButtonDisabled(true);
            }
          });
    });
    JS;
?>
<?= /** noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>
