<?php
/**
 *  Copyright © iMi digital GmbH, based on work by MageSpecialist
 *  See LICENSE for license details.
 */
use Magento\Framework\View\Helper\SecureHtmlRenderer;

/** @var $block IMI\FriendlyCaptcha\Block\Frontend\FriendlyCaptcha */
/** @var $secureRenderer SecureHtmlRenderer */

?>
<?php
$widgetId = $block->getWidgetId();
$scriptString = <<<SCRIPT
 'use strict';

    if (document.getElementById('newsletter-validate-detail')) {
        document.getElementById('newsletter-validate-detail').append(document.getElementById('{$widgetId}'));
    } else {
        document.getElementById('{$widgetId}').remove();
    }
SCRIPT;

?>
<?= /** noEscape */
$secureRenderer->renderTag('script', [], $scriptString, false) ?>
