name: ExtDN M2 Mess Detector
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpmd:
    name: M2 Mess Detector
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - uses: extdn/github-actions-m2/magento-mess-detector@master